name: "ecotechnologies.io"
description: "Technologies to help you live in harmony with nature"

# url: "http://ecotechnologies.github.io"

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true

prose:
  siteurl: "http://blog.weinberg.me"
  media: "images"
  metadata:
    _posts:
      - name: "layout"
        field:
          label: "layout"
          element: "text"
          value: "default"
      - name: "tags"
        field:
          element: "text"
          label: "Add Tags"
          value: "Pedal power"
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
          
            
   
